spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # input client id here
            client-secret: # input client secret here
            scope: profile,email,openid
            client-name: Oauth2DemoWebClient
  datasource:
    url: jdbc:h2:mem:oauth
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console